discord_api_key: <apikey>
discord_server_id: <serverid>
discord_forum_channel_id: <forumid>
discord_lock_thread: 14
discord_role: verified
network: kusama
substrate_wss: wss://kusama-rpc.polkadot.io